version: '3.7'

services:
  keycloak:
    image: fabian/keycloak:postgres
    container_name: keycloak
    networks:
      - keycloak-net
    ports:
      - 8089:8080
      - 8090:8443
    command: 
    - start
    - --optimized
    - --https-certificate-file=/opt/keycloak/certs/server.crt.pem
    - --https-certificate-key-file=/opt/keycloak/certs/server.key
    environment:
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=test1234
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    container_name: postgres
    networks:
      - keycloak-net
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=test1234
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 5s
      timeout: 5s
      retries: 5

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   networks:
  #     - keycloak-net
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - postgres

networks:
  keycloak-net:
    external: true